cat > dockerfile << 'EOF'FROM node:18 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM httpd:2.4
COPY --from=build /app/build /usr/local/apache2/htdocs/
RUN echo 'LoadModule proxy_module modules/mod_proxy.so' >> /usr/local/apache2/conf/httpd.conf && \
    echo 'LoadModule proxy_http_module modules/mod_proxy_http.so' >> /usr/local/apache2/conf/httpd.conf && \
    echo 'ProxyPass /api/ http://172.17.0.3:80/' >> /usr/local/apache2/conf/httpd.conf && \
    echo 'ProxyPassReverse /api/ http://172.17.0.3:80/' >> /usr/local/apache2/conf/httpd.conf
EXPOSE 80
CMD ["httpd-foreground"]
EOF
